#curl -X POST -H "Content-Type: application/json" -d '{"username": "kevinarm", "password": "vientos#123"}' http://127.0.0.1:8000/api/token/login/

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "kevinarm",
    "password": "vientos#123"
}


###
GET http://127.0.0.1:8000//api/v1/portfolio/certifications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEzMDUzNzE4LCJpYXQiOjE3MDQ0MTM3MTgsImp0aSI6ImNkMTQ5NmFlOTFlZTQ2N2VhZmE3YTdjMTBlM2Y4NmYwIiwidXNlcl9pZCI6MX0.ZTjLWEqlcsRjN71zHYpOtjF8y_Lr-yHzBV8X5gWKkK8