# Generated by Django 5.0.1 on 2024-01-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
    ]
