# Generated by Django 5.0.1 on 2024-01-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/knowledge'),
        ),
    ]
