# Generated by Django 5.0.1 on 2024-01-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experience_table_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('current', '-join_date')},
        ),
        migrations.AlterField(
            model_name='experience',
            name='left_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
