# Generated by Django 5.0.1 on 2024-01-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projectimage_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
