# Generated by Django 5.0.1 on 2024-01-03 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('job_position', models.CharField(max_length=300)),
                ('join_date', models.DateField()),
                ('left_date', models.DateField()),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=400)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.experience')),
            ],
        ),
    ]
