# Generated by Django 5.0.1 on 2024-01-03 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='experience_id',
        ),
        migrations.AddField(
            model_name='task',
            name='experience',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='experience.experience'),
            preserve_default=False,
        ),
    ]
